#!/bin/sh
#  0 14  *   *   *     
~/bin/download-rutracker-torrent.sh 5291059 > /home/pi/torrents-tmp/www.torrent; shasum=$(cat /home/pi/torrents/sha256sum.txt); new_chasum=$(sha256sum /home/pi/torrents-tmp/www.torrent | cut -d ' ' -f1); echo $new_chasum > /home/pi/torrents/sha256sum.txt; [ ${#new_chasum} != 0 ] && [ "$shasum" != "$new_chasum" ] && telegram-cli -WDR -l 0 -e "$(echo -e "msg vigvam $(cat ~/bin/new-torrent-message.txt | xargs)")" >/dev/null 2>&1; mv /home/pi/torrents-tmp/www.torrent /home/pi/torrents/www.torrent
